"""add surface and mod to finished_matches

Revision ID: 0518826e522a
Revises: 867755e0f38f
Create Date: 2026-08-27 08:10:53.005087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0518826e522a'
down_revision: Union[str, Sequence[str], None] = '867755e0f38f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("finished_matches", sa.Column("surface", sa.String(), nullable=True))
    op.add_column("finished_matches", sa.Column("mod", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("finished_matches", "mod")
    op.drop_column("finished_matches", "surface")
    # ### end Alembic commands ###
