"""add outfit_ratings table

Revision ID: 07c6bb4c1a08
Revises: 20260424180000
Create Date: 2026-06-30 11:48:54.905674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07c6bb4c1a08'
down_revision: Union[str, Sequence[str], None] = '20260424180000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outfit_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outfit_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('outfit_id', 'user_id', name='uq_outfit_rating_user')
    )
    op.create_index(op.f('ix_outfit_ratings_outfit_id'), 'outfit_ratings', ['outfit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outfit_ratings_outfit_id'), table_name='outfit_ratings')
    op.drop_table('outfit_ratings')
    # ### end Alembic commands ###
