"""add user_profiles table

Revision ID: 5ff7f62c0348
Revises: 20260417120000
Create Date: 2026-04-24 12:18:12.210387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ff7f62c0348'
down_revision: Union[str, Sequence[str], None] = '20260417120000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('tours', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('in_game_name', sa.String(length=100), nullable=True),
    sa.Column('player_name', sa.String(length=200), nullable=True),
    sa.Column('player_verified', sa.Boolean(), nullable=False),
    sa.Column('favorite_tennis_player', sa.String(length=200), nullable=True),
    sa.Column('favorite_tournament', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
