"""initial_schema

Revision ID: c64faa9b157b
Revises: 
Create Date: 2026-04-11 13:27:05.141804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c64faa9b157b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_finished_matches_created_at'), 'finished_matches', ['created_at'], unique=False)
    op.alter_column('guides', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('guides', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('guides_slug_key'), 'guides', type_='unique')
    op.drop_index(op.f('idx_guides_slug'), table_name='guides')
    op.drop_index(op.f('idx_guides_type'), table_name='guides')
    op.create_index(op.f('ix_guides_guide_type'), 'guides', ['guide_type'], unique=False)
    op.create_index(op.f('ix_guides_id'), 'guides', ['id'], unique=False)
    op.create_index(op.f('ix_guides_slug'), 'guides', ['slug'], unique=True)
    op.create_index(op.f('ix_guides_title'), 'guides', ['title'], unique=False)
    op.create_index(op.f('ix_outfits_id'), 'outfits', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outfits_id'), table_name='outfits')
    op.drop_index(op.f('ix_guides_title'), table_name='guides')
    op.drop_index(op.f('ix_guides_slug'), table_name='guides')
    op.drop_index(op.f('ix_guides_id'), table_name='guides')
    op.drop_index(op.f('ix_guides_guide_type'), table_name='guides')
    op.create_index(op.f('idx_guides_type'), 'guides', ['guide_type'], unique=False)
    op.create_index(op.f('idx_guides_slug'), 'guides', ['slug'], unique=False)
    op.create_unique_constraint(op.f('guides_slug_key'), 'guides', ['slug'], postgresql_nulls_not_distinct=False)
    op.alter_column('guides', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('guides', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_finished_matches_created_at'), table_name='finished_matches')
    # ### end Alembic commands ###
